---
# .sops.yaml - SOPS configuration file
# This file defines the key groups and rules for encrypting secrets

# Define key groups for different environments
keys:
  # Users
  - &user_austin age12eypf50tnxw4axrptwn3klaw2cpt4jflky7zhp30cd0cueacadmstrpyg0
  # Add more users as needed
  # - &user_jessica age1...

  # Machines
  - &machine_monaco age1ehkc2h4v5lgwc5sask4rrs6sy77ctkfvx47dgc7sue8e7ua5du6qd9tr28
  - &machine_plutonium age1znyc625kgd89dm729lh7f85yws2xp58qqx9sfqmp8kuthh97gq0q9k9c57
  - &machine_siberia age1760ks8ehyhfdvf3a38ue95u2fk0f5mg2gy7gdm7mf0lzgavfqg3qe7q4jg
  - &machine_silver age19vlzdxhfvdl9dzwepmuq9z79pyafzteg0uy463xvjqlgn3xcgc3qqdnq2k

# Creation rules for different paths
creation_rules:
  # Common secrets
  - path_regex: systems/common/.*sops\.yaml$
    key_groups:
      - age:
          - *user_austin
        # Add more users as needed

  # Machine-specific secrets
  - path_regex: machines/monaco/.*sops\.yaml$
    key_groups:
      - age:
          - *user_austin
          - *machine_monaco

  - path_regex: machines/plutonium/.*sops\.yaml$
    key_groups:
      - age:
          - *user_austin
          - *machine_plutonium

  - path_regex: machines/siberia/.*sops\.yaml$
    key_groups:
      - age:
          - *user_austin
          - *machine_siberia

  - path_regex: machines/silver/.*sops\.yaml$
    key_groups:
      - age:
          - *user_austin
          - *machine_silver

  # User-specific secrets
  - path_regex: users/austin/.*sops\.yaml$
    key_groups:
      - age:
          - *user_austin

  # Add more user-specific paths as needed
  # - path_regex: users/jessica/.*sops\.yaml$
  #   key_groups:
  #   - age:
  #     - *user_jessica
