---
# .sops.yaml - SOPS configuration file
# This file defines the key groups and rules for encrypting secrets

# Define key groups for different environments
keys:
  # Users
  - &user_austin age1yubikey1...
  # Add more users as needed
  # - &user_jessica age1...

  # Machines
  - &machine_monaco age1...
  - &machine_plutonium age1...
  - &machine_siberia age1...
  - &machine_silver age1...

# Creation rules for different paths
creation_rules:
  # Common secrets
  - path_regex: systems/common/.*sops\.yaml$
    key_groups:
    - age:
      - *user_austin
      # Add more users as needed

  # Machine-specific secrets
  - path_regex: machines/monaco/.*sops\.yaml$
    key_groups:
    - age:
      - *user_austin
      - *machine_monaco

  - path_regex: machines/plutonium/.*sops\.yaml$
    key_groups:
    - age:
      - *user_austin
      - *machine_plutonium

  - path_regex: machines/siberia/.*sops\.yaml$
    key_groups:
    - age:
      - *user_austin
      - *machine_siberia

  - path_regex: machines/silver/.*sops\.yaml$
    key_groups:
    - age:
      - *user_austin
      - *machine_silver

  # User-specific secrets
  - path_regex: users/austin/.*sops\.yaml$
    key_groups:
    - age:
      - *user_austin

  # Add more user-specific paths as needed
  # - path_regex: users/jessica/.*sops\.yaml$
  #   key_groups:
  #   - age:
  #     - *user_jessica