---
# .sops.yaml - SOPS configuration file
# This file defines the key groups and rules for encrypting secrets

# Define key groups for different environments
keys:
  # Users
  - &user_austin age1yubikey1...
  # Add more users as needed
  # - &user_jessica age1...

  # Machines
  - &machine_monaco age1...
  - &machine_plutonium age1...
  - &machine_siberia age1...
  - &machine_silver age1...

# Creation rules for different paths
creation_rules:
  # Default rule for all secrets
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *user_austin
      # Add more users as needed

  # Machine-specific secrets
  - path_regex: secrets/machines/monaco/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *user_austin
      - *machine_monaco

  - path_regex: secrets/machines/plutonium/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *user_austin
      - *machine_plutonium

  - path_regex: secrets/machines/siberia/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *user_austin
      - *machine_siberia

  - path_regex: secrets/machines/silver/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *user_austin
      - *machine_silver

  # User-specific secrets
  - path_regex: secrets/users/austin/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *user_austin

  # Add more user-specific paths as needed
  # - path_regex: secrets/users/jessica/[^/]+\.(yaml|json|env|ini)$
  #   key_groups:
  #   - age:
  #     - *user_jessica