# machines/silver/hardware-configuration.nix
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  # Blacklist b43 driver to prevent race condition with wl (broadcom_sta)
  # BCM4360 is not supported by b43, which causes intermittent WiFi failures
  # when b43 attempts to claim the device first and blocks wl from loading
  boot.blacklistedKernelModules = [ "b43" "b43legacy" "ssb" "bcma" ];

  # Modprobe configuration to ensure wl driver is preferred
  boot.extraModprobeConfig = ''
    # Blacklist b43 and related modules for BCM4360 WiFi chip
    # The b43 driver does not support BCM4360 (802.11ac) and creates
    # a race condition with the wl (broadcom_sta) driver
    blacklist b43
    blacklist b43legacy
    blacklist ssb
    blacklist bcma
  '';

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/1b161ea5-49c8-4b4a-a6f5-960662c8e000";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/C5DE-EE37";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/32d31193-f0e9-4a15-8ae4-fa7b35f543d5"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
