# users/austin/nixos/hyprland/matugen.nix
# matugen color extraction and theming configuration
{ pkgs, lib, config, ... }:

let
  wallpaperDir = "${config.home.homeDirectory}/Pictures/Wallpapers/Favorites";

  # matugen config file
  matugenConfig = pkgs.writeText "matugen-config.toml" ''
    [config]
    reload_apps = false
    
    [templates]
    hyprland = { input_path = "${config.xdg.configHome}/matugen/templates/hyprland-colors.tpl", output_path = "${config.xdg.cacheHome}/matugen/hyprland-colors.conf" }
    waybar = { input_path = "${config.xdg.configHome}/matugen/templates/waybar-colors.css", output_path = "${config.xdg.configHome}/waybar/colors.css" }
    wlogout = { input_path = "${config.xdg.configHome}/matugen/templates/wlogout-colors.css", output_path = "${config.xdg.configHome}/wlogout/colors.css" }
    mako = { input_path = "${config.xdg.configHome}/matugen/templates/mako-config.tpl", output_path = "${config.xdg.configHome}/mako/config" }
    wofi = { input_path = "${config.xdg.configHome}/matugen/templates/wofi-colors.css", output_path = "${config.xdg.configHome}/wofi/colors.css" }
    ghostty = { input_path = "${config.xdg.configHome}/matugen/templates/ghostty-colors.conf", output_path = "${config.xdg.configHome}/ghostty/colors.conf" }
    tmux = { input_path = "${config.xdg.configHome}/matugen/templates/tmux-colors.conf", output_path = "${config.xdg.configHome}/tmux/tmux-colors.conf" }
    nixvim = { input_path = "${config.xdg.configHome}/matugen/templates/nvim-matugen.lua", output_path = "${config.xdg.configHome}/nvim/lua/generated/matugen.lua" }
    opencode = { input_path = "${config.xdg.configHome}/matugen/templates/opencode-theme.json", output_path = "${config.xdg.configHome}/opencode/themes/wallpaper.json" }
  '';
in
{
  # wofi configuration file with matugen colors
  home.file."${config.xdg.configHome}/wofi/config".text = ''
    # wofi configuration
    width=600
    height=400
    location=center
    show=drun
    prompt=Search...
    filter_rate=100
    allow_markup=true
    no_actions=true
    halign=fill
    orientation=vertical
    content_halign=fill
    insensitive=true
    allow_images=true
    image_size=24
    columns=1
    stylesheet=${config.xdg.configHome}/wofi/colors.css
  '';

  # Create matugen config directory and templates
  home.file = {
    # matugen config
    "${config.xdg.configHome}/matugen/config.toml".source = matugenConfig;

    # OpenCode TUI configuration
    "${config.xdg.configHome}/opencode/tui.json".text = builtins.toJSON {
      theme = "wallpaper";
    };

    # Hyprland color template
    "${config.xdg.configHome}/matugen/templates/hyprland-colors.tpl".text = ''
      # Hyprland colors generated by matugen
      general {
        col.active_border = rgba({{colors.primary.default.hex_stripped}}ff) rgba({{colors.tertiary.default.hex_stripped}}ff) 45deg
        col.inactive_border = rgba({{colors.surface_variant.default.hex_stripped}}ff)
      }
      
      decoration {
        shadow {
          color = rgba({{colors.shadow.default.hex_stripped}}aa)
          color_inactive = rgba({{colors.shadow.default.hex_stripped}}55)
        }
      }
    '';

    # Waybar color template
    "${config.xdg.configHome}/matugen/templates/waybar-colors.css".text = ''
      /* Waybar colors generated by matugen */
      @define-color bg {{colors.background.default.hex}};
      @define-color surface {{colors.surface.default.hex}};
      @define-color surface-alt {{colors.surface_container_high.default.hex}};
      @define-color fg {{colors.on_surface.default.hex}};
      @define-color accent {{colors.primary.default.hex}};
      @define-color accent-alt {{colors.tertiary.default.hex}};
      @define-color accent-soft {{colors.secondary_container.default.hex}};
      @define-color on-accent {{colors.on_primary.default.hex}};
      @define-color muted {{colors.outline.default.hex}};
      @define-color border {{colors.outline_variant.default.hex}};
      @define-color warning {{colors.secondary.default.hex}};
      @define-color urgent {{colors.error.default.hex}};
       
      * {
        color: @fg;
      }
       
      #workspaces button.active {
        background-color: @accent;
        color: @on-accent;
      }

      #battery.warning,
      #temperature.critical,
      #network.disconnected {
        background-color: @warning;
        color: @bg;
      }
    '';

    # wlogout color template
    "${config.xdg.configHome}/matugen/templates/wlogout-colors.css".text = ''
      /* wlogout colors generated by matugen */
      @define-color bg {{colors.background.default.hex}};
      @define-color surface {{colors.surface.default.hex}};
      @define-color surface-alt {{colors.surface_container_high.default.hex}};
      @define-color fg {{colors.on_surface.default.hex}};
      @define-color accent {{colors.primary.default.hex}};
      @define-color accent-alt {{colors.tertiary.default.hex}};
      @define-color on-accent {{colors.on_primary.default.hex}};
      @define-color border {{colors.outline_variant.default.hex}};
      @define-color urgent {{colors.error.default.hex}};
    '';

    # mako config template
    "${config.xdg.configHome}/matugen/templates/mako-config.tpl".text = ''
      # mako config generated by matugen
      background-color={{colors.surface_container_high.default.hex}}
      text-color={{colors.on_surface.default.hex}}
      border-color={{colors.primary.default.hex}}
      progress-color=over {{colors.secondary_container.default.hex}}
      default-timeout=5000
      group-by=summary
      max-visible=5
      border-size=2
      border-radius=8
      font=Sans 10
    '';

    # wofi color template
    "${config.xdg.configHome}/matugen/templates/wofi-colors.css".text = ''
      /* wofi colors generated by matugen */
      window {
        background-color: {{colors.surface_container.default.hex}};
        color: {{colors.on_surface.default.hex}};
        border: 2px solid {{colors.primary.default.hex}};
        border-radius: 12px;
      }
      
      #input {
        background-color: {{colors.surface_container_high.default.hex}};
        color: {{colors.on_surface.default.hex}};
        border: 2px solid {{colors.outline_variant.default.hex}};
        border-radius: 10px;
        margin: 10px;
        padding: 10px 12px;
      }

      #inner-box {
        margin: 8px;
      }

      #entry {
        border-radius: 10px;
        margin: 4px 8px;
        padding: 10px 12px;
      }

      #entry:nth-child(even) {
        background-color: {{colors.surface_container_high.default.hex}};
      }
      
      #entry:selected {
        background-color: {{colors.primary.default.hex}};
        color: {{colors.on_primary.default.hex}};
        outline: none;
      }

      #text:selected,
      #img:selected {
        color: {{colors.on_primary.default.hex}};
      }
    '';

    # ghostty color template
    "${config.xdg.configHome}/matugen/templates/ghostty-colors.conf".text = ''
      # Ghostty colors generated by matugen
      background = {{colors.background.default.hex}}
      foreground = {{colors.on_background.default.hex}}
      cursor-color = {{colors.primary.default.hex}}
      cursor-text = {{colors.on_primary.default.hex}}
      selection-background = {{colors.secondary_container.default.hex}}
      selection-foreground = {{colors.on_secondary_container.default.hex}}
      search-background = {{colors.tertiary.default.hex}}
      search-foreground = {{colors.on_tertiary.default.hex}}
      search-selected-background = {{colors.primary.default.hex}}
      search-selected-foreground = {{colors.on_primary.default.hex}}
      split-divider-color = {{colors.outline_variant.default.hex}}
      unfocused-split-fill = {{colors.surface_container_low.default.hex}}
      
      palette = 0={{colors.surface.default.hex}}
      palette = 1={{colors.error.default.hex}}
      palette = 2={{colors.tertiary.default.hex}}
      palette = 3={{colors.secondary.default.hex}}
      palette = 4={{colors.primary.default.hex}}
      palette = 5={{colors.inverse_primary.default.hex}}
      palette = 6={{colors.primary_fixed_dim.default.hex}}
      palette = 7={{colors.on_surface.default.hex}}
      palette = 8={{colors.outline.default.hex}}
      palette = 9={{colors.error.default.hex}}
      palette = 10={{colors.tertiary.default.hex}}
      palette = 11={{colors.secondary.default.hex}}
      palette = 12={{colors.primary.default.hex}}
      palette = 13={{colors.inverse_primary.default.hex}}
      palette = 14={{colors.primary_fixed_dim.default.hex}}
      palette = 15={{colors.on_surface.default.hex}}
    '';

    # tmux color template
    "${config.xdg.configHome}/matugen/templates/tmux-colors.conf".text = ''
      # tmux colors generated by matugen
      set -g @matugen_bg '{{colors.background.default.hex}}'
      set -g @matugen_surface '{{colors.surface.default.hex}}'
      set -g @matugen_surface_alt '{{colors.surface_container_high.default.hex}}'
      set -g @matugen_fg '{{colors.on_surface.default.hex}}'
      set -g @matugen_accent '{{colors.primary.default.hex}}'
      set -g @matugen_accent_alt '{{colors.tertiary.default.hex}}'
      set -g @matugen_border '{{colors.outline_variant.default.hex}}'
      set -g @matugen_urgent '{{colors.error.default.hex}}'

      set -g status-style "bg=#{@matugen_surface},fg=#{@matugen_fg}"
      set -g message-style "bg=#{@matugen_accent},fg={{colors.on_primary.default.hex}}"
      set -g message-command-style "bg=#{@matugen_accent_alt},fg={{colors.on_tertiary.default.hex}}"
      set -g pane-border-style "fg=#{@matugen_border}"
      set -g pane-active-border-style "fg=#{@matugen_accent}"
      set -g status-left-style "bg=#{@matugen_accent},fg={{colors.on_primary.default.hex}}"
      set -g status-right-style "bg=#{@matugen_surface_alt},fg=#{@matugen_fg}"
      set -g window-status-style "bg=#{@matugen_surface},fg=#{@matugen_fg}"
      set -g window-status-current-style "bg=#{@matugen_accent_alt},fg={{colors.on_tertiary.default.hex}},bold"
      set -g window-status-activity-style "bg=#{@matugen_surface_alt},fg=#{@matugen_accent}"
      set -g window-status-bell-style "bg=#{@matugen_urgent},fg={{colors.on_error.default.hex}},bold"
    '';

    # Neovim wallpaper theme template
    "${config.xdg.configHome}/matugen/templates/nvim-matugen.lua".text = ''
      -- Neovim colors generated by matugen
      local c = {
        bg = "{{colors.background.default.hex}}",
        surface = "{{colors.surface.default.hex}}",
        surface_alt = "{{colors.surface_container_high.default.hex}}",
        fg = "{{colors.on_surface.default.hex}}",
        muted = "{{colors.outline.default.hex}}",
        border = "{{colors.outline_variant.default.hex}}",
        accent = "{{colors.primary.default.hex}}",
        accent_alt = "{{colors.tertiary.default.hex}}",
        accent_soft = "{{colors.secondary_container.default.hex}}",
        on_accent = "{{colors.on_primary.default.hex}}",
        ok = "{{colors.secondary.default.hex}}",
        warn = "{{colors.tertiary.default.hex}}",
        err = "{{colors.error.default.hex}}",
      }

      vim.o.termguicolors = true
      vim.g.colors_name = "matugen-wallpaper"

      local set = vim.api.nvim_set_hl
      set(0, "Normal", { fg = c.fg, bg = c.bg })
      set(0, "NormalFloat", { fg = c.fg, bg = c.surface })
      set(0, "FloatBorder", { fg = c.accent, bg = c.surface })
      set(0, "WinSeparator", { fg = c.border, bg = c.bg })
      set(0, "CursorLine", { bg = c.surface })
      set(0, "CursorLineNr", { fg = c.accent, bold = true })
      set(0, "Visual", { bg = c.accent_soft, fg = c.fg })
      set(0, "Search", { bg = c.accent, fg = c.on_accent })
      set(0, "IncSearch", { bg = c.accent_alt, fg = c.bg })
      set(0, "LineNr", { fg = c.muted })
      set(0, "Pmenu", { fg = c.fg, bg = c.surface })
      set(0, "PmenuSel", { fg = c.on_accent, bg = c.accent })
      set(0, "PmenuSbar", { bg = c.surface_alt })
      set(0, "PmenuThumb", { bg = c.accent_alt })
      set(0, "StatusLine", { fg = c.fg, bg = c.surface_alt })
      set(0, "StatusLineNC", { fg = c.muted, bg = c.surface })
      set(0, "TabLine", { fg = c.fg, bg = c.surface })
      set(0, "TabLineSel", { fg = c.on_accent, bg = c.accent })
      set(0, "TabLineFill", { bg = c.bg })
      set(0, "DiagnosticError", { fg = c.err })
      set(0, "DiagnosticWarn", { fg = c.warn })
      set(0, "DiagnosticInfo", { fg = c.accent })
      set(0, "DiagnosticHint", { fg = c.ok })
      set(0, "DiagnosticVirtualTextError", { fg = c.err, bg = c.surface })
      set(0, "DiagnosticVirtualTextWarn", { fg = c.warn, bg = c.surface })
      set(0, "DiagnosticVirtualTextInfo", { fg = c.accent, bg = c.surface })
      set(0, "DiagnosticVirtualTextHint", { fg = c.ok, bg = c.surface })
      set(0, "BufferLineFill", { bg = c.bg })
      set(0, "BufferLineBackground", { fg = c.muted, bg = c.surface })
      set(0, "BufferLineBufferSelected", { fg = c.fg, bg = c.surface_alt, bold = true })
      set(0, "BufferLineIndicatorSelected", { fg = c.accent, bg = c.surface_alt })
      set(0, "BufferLineSeparator", { fg = c.bg, bg = c.bg })
      set(0, "BufferLineSeparatorSelected", { fg = c.bg, bg = c.surface_alt })
      set(0, "NoiceCmdlinePopupBorder", { fg = c.accent, bg = c.surface })
      set(0, "NoiceConfirmBorder", { fg = c.accent_alt, bg = c.surface })
      set(0, "NotifyBackground", { bg = c.surface })

      return c
    '';

    # OpenCode theme template
    "${config.xdg.configHome}/matugen/templates/opencode-theme.json".text = ''
      {
        "$schema": "https://opencode.ai/theme.json",
        "theme": {
          "primary": "{{colors.primary.default.hex}}",
          "secondary": "{{colors.tertiary.default.hex}}",
          "accent": "{{colors.primary_container.default.hex}}",
          "text": "{{colors.on_surface.default.hex}}",
          "textMuted": "{{colors.outline.default.hex}}",
          "background": "{{colors.background.default.hex}}",
          "backgroundPanel": "{{colors.surface.default.hex}}",
          "backgroundElement": "{{colors.surface_container_high.default.hex}}",
          "border": "{{colors.outline_variant.default.hex}}",
          "borderActive": "{{colors.primary.default.hex}}",
          "borderSubtle": "{{colors.surface_container_highest.default.hex}}",
          "error": "{{colors.error.default.hex}}",
          "warning": "{{colors.secondary.default.hex}}",
          "success": "{{colors.primary.default.hex}}",
          "info": "{{colors.tertiary.default.hex}}",
          "diffAdded": "{{colors.primary.default.hex}}",
          "diffRemoved": "{{colors.error.default.hex}}",
          "diffContext": "{{colors.outline.default.hex}}",
          "diffHunkHeader": "{{colors.tertiary.default.hex}}",
          "diffHighlightAdded": "{{colors.primary_container.default.hex}}",
          "diffHighlightRemoved": "{{colors.error_container.default.hex}}",
          "diffAddedBg": "{{colors.primary_container.default.hex}}",
          "diffRemovedBg": "{{colors.error_container.default.hex}}",
          "diffContextBg": "{{colors.surface.default.hex}}",
          "diffLineNumber": "{{colors.outline.default.hex}}",
          "diffAddedLineNumberBg": "{{colors.primary_fixed_dim.default.hex}}",
          "diffRemovedLineNumberBg": "{{colors.error.default.hex}}",
          "syntaxComment": "{{colors.outline.default.hex}}",
          "syntaxKeyword": "{{colors.tertiary.default.hex}}",
          "syntaxFunction": "{{colors.primary.default.hex}}",
          "syntaxVariable": "{{colors.on_surface.default.hex}}",
          "syntaxString": "{{colors.secondary.default.hex}}",
          "syntaxNumber": "{{colors.tertiary.default.hex}}",
          "syntaxType": "{{colors.primary_fixed_dim.default.hex}}",
          "syntaxOperator": "{{colors.primary.default.hex}}",
          "syntaxPunctuation": "{{colors.outline.default.hex}}"
        }
      }
    '';
  };

  # Ensure directories exist
  home.activation.createMatugenDirs = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p "${config.xdg.configHome}/matugen/templates"
    mkdir -p "${config.xdg.cacheHome}/matugen"
    mkdir -p "${config.xdg.configHome}/waybar"
    mkdir -p "${config.xdg.configHome}/wlogout"
    mkdir -p "${config.xdg.configHome}/mako"
    mkdir -p "${config.xdg.configHome}/wofi"
    mkdir -p "${config.xdg.configHome}/ghostty"
    mkdir -p "${config.xdg.configHome}/tmux"
    mkdir -p "${config.xdg.configHome}/nvim/lua/generated"
    mkdir -p "${config.xdg.configHome}/opencode/themes"
  '';

  # Seed matugen outputs before Hyprland starts so `source = ...` is always valid.
  # Prefer a real random wallpaper from Favorites; fall back to a minimal valid file.
  home.activation.seedMatugenTheme = lib.hm.dag.entryAfter [ "createMatugenDirs" ] ''
    cache_dir="${config.xdg.cacheHome}/matugen"
    hypr_file="$cache_dir/hyprland-colors.conf"
    wallpaper_dir="${wallpaperDir}"
    seeded=0

    mkdir -p "$cache_dir"

    if [ -d "$wallpaper_dir" ]; then
      wallpaper="$(${pkgs.findutils}/bin/find "$wallpaper_dir" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) | ${pkgs.coreutils}/bin/shuf -n 1 || true)"

      if [ -n "$wallpaper" ]; then
        if ${pkgs.matugen}/bin/matugen image "$wallpaper" --config "${config.xdg.configHome}/matugen/config.toml"; then
          if [ -s "$hypr_file" ]; then
            seeded=1
          fi
        fi
      fi
    fi

    if [ "$seeded" -ne 1 ]; then
      printf '%s\n' '# fallback matugen seed file' > "$hypr_file"
    fi
  '';
}
