# users/austin/nixos/hyprland/matugen.nix
# matugen color extraction and theming configuration
{ pkgs, lib, config, ... }:

let
  # Tokyo Night base16 fallback colors
  tokyoNight = {
    background = "#1a1b26";
    foreground = "#c0caf5";
    cursor = "#c0caf5";
    color0 = "#15161e";
    color1 = "#f7768e";
    color2 = "#9ece6a";
    color3 = "#e0af68";
    color4 = "#7aa2f7";
    color5 = "#bb9af7";
    color6 = "#7dcfff";
    color7 = "#a9b1d6";
    color8 = "#414868";
    color9 = "#f7768e";
    color10 = "#9ece6a";
    color11 = "#e0af68";
    color12 = "#7aa2f7";
    color13 = "#bb9af7";
    color14 = "#7dcfff";
    color15 = "#c0caf5";
  };

  # matugen config file
  matugenConfig = pkgs.writeText "matugen-config.toml" ''
    [config]
    reload_apps = false
    
    [templates]
    hyprland = { input_path = "${config.xdg.configHome}/matugen/templates/hyprland-colors.tpl", output_path = "${config.xdg.cacheHome}/matugen/hyprland-colors.conf" }
    waybar = { input_path = "${config.xdg.configHome}/matugen/templates/waybar-colors.css", output_path = "${config.xdg.configHome}/waybar/colors.css" }
    mako = { input_path = "${config.xdg.configHome}/matugen/templates/mako-config.tpl", output_path = "${config.xdg.configHome}/mako/config" }
    wofi = { input_path = "${config.xdg.configHome}/matugen/templates/wofi-colors.css", output_path = "${config.xdg.configHome}/wofi/colors.css" }
    ghostty = { input_path = "${config.xdg.configHome}/matugen/templates/ghostty-colors.conf", output_path = "${config.xdg.configHome}/ghostty/colors.conf" }
  '';
in
{
  # wofi configuration file with matugen colors
  home.file."${config.xdg.configHome}/wofi/config".text = ''
    # wofi configuration
    width=600
    height=400
    location=center
    show=drun
    prompt=Search...
    filter_rate=100
    allow_markup=true
    no_actions=true
    halign=fill
    orientation=vertical
    content_halign=fill
    insensitive=true
    allow_images=true
    image_size=24
    columns=1
    stylesheet=${config.xdg.configHome}/wofi/colors.css
  '';

  # Create matugen config directory and templates
  home.file = {
    # matugen config
    "${config.xdg.configHome}/matugen/config.toml".source = matugenConfig;

    # Hyprland color template
    "${config.xdg.configHome}/matugen/templates/hyprland-colors.tpl".text = ''
      # Hyprland colors generated by matugen
      general {
        col.active_border = rgba({{colors.primary.default.hex_stripped}}ff) rgba({{colors.tertiary.default.hex_stripped}}ff) 45deg
        col.inactive_border = rgba({{colors.surface_variant.default.hex_stripped}}ff)
      }
      
      decoration {
        col.shadow = rgba({{colors.shadow.default.hex_stripped}}aa)
        col.shadow_inactive = rgba({{colors.shadow.default.hex_stripped}}55)
      }
    '';

    # Waybar color template
    "${config.xdg.configHome}/matugen/templates/waybar-colors.css".text = ''
      /* Waybar colors generated by matugen */
      @define-color bg {{colors.surface.default.hex}};
      @define-color fg {{colors.on_surface.default.hex}};
      @define-color accent {{colors.primary.default.hex}};
      @define-color muted {{colors.outline.default.hex}};
      
      * {
        background-color: @bg;
        color: @fg;
      }
      
      #workspaces button.active {
        background-color: @accent;
      }
    '';

    # mako config template
    "${config.xdg.configHome}/matugen/templates/mako-config.tpl".text = ''
      # mako config generated by matugen
      background-color={{colors.surface.default.hex}}
      text-color={{colors.on_surface.default.hex}}
      border-color={{colors.primary.default.hex}}
      border-size=2
      border-radius=8
      default-timeout=5000
      font=Sans 10
    '';

    # wofi color template
    "${config.xdg.configHome}/matugen/templates/wofi-colors.css".text = ''
      /* wofi colors generated by matugen */
      window {
        background-color: {{colors.surface.default.hex}};
        color: {{colors.on_surface.default.hex}};
        border: 2px solid {{colors.primary.default.hex}};
        border-radius: 8px;
      }
      
      #input {
        background-color: {{colors.surface_variant.default.hex}};
        color: {{colors.on_surface.default.hex}};
        border: 1px solid {{colors.outline.default.hex}};
      }
      
      #entry:selected {
        background-color: {{colors.primary.default.hex}};
        color: {{colors.on_primary.default.hex}};
      }
    '';

    # ghostty color template
    "${config.xdg.configHome}/matugen/templates/ghostty-colors.conf".text = ''
      # Ghostty colors generated by matugen
      background = {{colors.background.default.hex}}
      foreground = {{colors.on_background.default.hex}}
      
      palette = 0={{colors.surface.default.hex}}
      palette = 1={{colors.error.default.hex}}
      palette = 2={{colors.tertiary.default.hex}}
      palette = 3={{colors.secondary.default.hex}}
      palette = 4={{colors.primary.default.hex}}
      palette = 5={{colors.inverse_primary.default.hex}}
      palette = 6={{colors.primary_fixed_dim.default.hex}}
      palette = 7={{colors.on_surface.default.hex}}
      palette = 8={{colors.outline.default.hex}}
      palette = 9={{colors.error.default.hex}}
      palette = 10={{colors.tertiary.default.hex}}
      palette = 11={{colors.secondary.default.hex}}
      palette = 12={{colors.primary.default.hex}}
      palette = 13={{colors.inverse_primary.default.hex}}
      palette = 14={{colors.primary_fixed_dim.default.hex}}
      palette = 15={{colors.on_surface.default.hex}}
    '';
  };

  # Ensure directories exist
  home.activation.createMatugenDirs = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p "${config.xdg.configHome}/matugen/templates"
    mkdir -p "${config.xdg.cacheHome}/matugen"
    mkdir -p "${config.xdg.configHome}/waybar"
    mkdir -p "${config.xdg.configHome}/mako"
    mkdir -p "${config.xdg.configHome}/wofi"
    mkdir -p "${config.xdg.configHome}/ghostty"
  '';
}
