# users/austin/nixos/hyprland/matugen.nix
# matugen color extraction and theming configuration
{ pkgs, lib, config, ... }:

let
  wallpaperDir = "${config.home.homeDirectory}/Pictures/Wallpapers/Favorites";

  # matugen config file
  matugenConfig = pkgs.writeText "matugen-config.toml" ''
    [config]
    reload_apps = false
    
    [templates]
    hyprland = { input_path = "${config.xdg.configHome}/matugen/templates/hyprland-colors.tpl", output_path = "${config.xdg.cacheHome}/matugen/hyprland-colors.conf" }
    waybar = { input_path = "${config.xdg.configHome}/matugen/templates/waybar-colors.css", output_path = "${config.xdg.configHome}/waybar/colors.css" }
    wlogout = { input_path = "${config.xdg.configHome}/matugen/templates/wlogout-colors.css", output_path = "${config.xdg.configHome}/wlogout/colors.css" }
    mako = { input_path = "${config.xdg.configHome}/matugen/templates/mako-config.tpl", output_path = "${config.xdg.configHome}/mako/config" }
    wofi = { input_path = "${config.xdg.configHome}/matugen/templates/wofi-colors.css", output_path = "${config.xdg.configHome}/wofi/colors.css" }
    ghostty = { input_path = "${config.xdg.configHome}/matugen/templates/ghostty-colors.conf", output_path = "${config.xdg.configHome}/ghostty/colors.conf" }
    ohmyposh = { input_path = "${config.xdg.configHome}/matugen/templates/ohmyposh-wallpaper.json", output_path = "${config.xdg.configHome}/oh-my-posh/wallpaper.json" }
    tmux = { input_path = "${config.xdg.configHome}/matugen/templates/tmux-colors.conf", output_path = "${config.xdg.configHome}/tmux/tmux-colors.conf" }
    nixvim = { input_path = "${config.xdg.configHome}/matugen/templates/nvim-matugen.lua", output_path = "${config.xdg.configHome}/nvim/lua/generated/matugen.lua" }
    opencode = { input_path = "${config.xdg.configHome}/matugen/templates/opencode-theme.json", output_path = "${config.xdg.configHome}/opencode/themes/wallpaper.json" }
  '';
in
{
  # wofi configuration file with matugen colors
  home.file."${config.xdg.configHome}/wofi/config".text = ''
    # wofi configuration
    width=600
    height=400
    location=center
    show=drun
    prompt=Search...
    filter_rate=100
    allow_markup=true
    no_actions=true
    halign=fill
    orientation=vertical
    content_halign=fill
    insensitive=true
    allow_images=true
    image_size=24
    columns=1
    stylesheet=${config.xdg.configHome}/wofi/colors.css
  '';

  # Create matugen config directory and templates
  home.file = {
    # matugen config
    "${config.xdg.configHome}/matugen/config.toml".source = matugenConfig;

    # Hyprland color template
    "${config.xdg.configHome}/matugen/templates/hyprland-colors.tpl".text = ''
      # Hyprland colors generated by matugen
      general {
        col.active_border = rgba({{colors.primary.default.hex_stripped}}ff) rgba({{colors.tertiary.default.hex_stripped}}ff) 45deg
        col.inactive_border = rgba({{colors.surface_variant.default.hex_stripped}}ff)
      }
      
      decoration {
        shadow {
          color = rgba({{colors.shadow.default.hex_stripped}}aa)
          color_inactive = rgba({{colors.shadow.default.hex_stripped}}55)
        }
      }
    '';

    # Waybar color template
    "${config.xdg.configHome}/matugen/templates/waybar-colors.css".text = ''
      /* Waybar colors generated by matugen */
      @define-color bg {{colors.background.default.hex}};
      @define-color surface {{colors.surface.default.hex}};
      @define-color surface-alt {{colors.surface_container_high.default.hex}};
      @define-color fg {{colors.on_surface.default.hex}};
      @define-color accent {{colors.primary.default.hex}};
      @define-color accent-alt {{colors.tertiary.default.hex}};
      @define-color accent-soft {{colors.secondary_container.default.hex}};
      @define-color on-accent {{colors.on_primary.default.hex}};
      @define-color muted {{colors.outline.default.hex}};
      @define-color border {{colors.outline_variant.default.hex}};
      @define-color warning {{colors.secondary.default.hex}};
      @define-color urgent {{colors.error.default.hex}};
       
      * {
        color: @fg;
      }
       
      #workspaces button.active {
        background-color: @accent;
        color: @on-accent;
      }

      #battery.warning,
      #temperature.critical,
      #network.disconnected {
        background-color: @warning;
        color: @bg;
      }
    '';

    # wlogout color template
    "${config.xdg.configHome}/matugen/templates/wlogout-colors.css".text = ''
      /* wlogout colors generated by matugen */
      @define-color bg {{colors.background.default.hex}};
      @define-color surface {{colors.surface.default.hex}};
      @define-color surface-alt {{colors.surface_container_high.default.hex}};
      @define-color fg {{colors.on_surface.default.hex}};
      @define-color accent {{colors.primary.default.hex}};
      @define-color accent-alt {{colors.tertiary.default.hex}};
      @define-color on-accent {{colors.on_primary.default.hex}};
      @define-color border {{colors.outline_variant.default.hex}};
      @define-color urgent {{colors.error.default.hex}};
    '';

    # mako config template
    "${config.xdg.configHome}/matugen/templates/mako-config.tpl".text = ''
      # mako config generated by matugen
      background-color={{colors.surface_container_high.default.hex}}
      text-color={{colors.on_surface.default.hex}}
      border-color={{colors.primary.default.hex}}
      progress-color=over {{colors.secondary_container.default.hex}}
      default-timeout=5000
      group-by=summary
      max-visible=5
      border-size=2
      border-radius=8
      font=Sans 10
    '';

    # wofi color template
    "${config.xdg.configHome}/matugen/templates/wofi-colors.css".text = ''
      /* wofi colors generated by matugen */
      window {
        background-color: {{colors.surface_container.default.hex}};
        color: {{colors.on_surface.default.hex}};
        border: 2px solid {{colors.primary.default.hex}};
        border-radius: 12px;
      }
      
      #input {
        background-color: {{colors.surface_container_high.default.hex}};
        color: {{colors.on_surface.default.hex}};
        border: 2px solid {{colors.outline_variant.default.hex}};
        border-radius: 10px;
        margin: 10px;
        padding: 10px 12px;
      }

      #inner-box {
        margin: 8px;
      }

      #entry {
        border-radius: 10px;
        margin: 4px 8px;
        padding: 10px 12px;
      }

      #entry:nth-child(even) {
        background-color: {{colors.surface_container_high.default.hex}};
      }
      
      #entry:selected {
        background-color: {{colors.primary.default.hex}};
        color: {{colors.on_primary.default.hex}};
        outline: none;
      }

      #text:selected,
      #img:selected {
        color: {{colors.on_primary.default.hex}};
      }
    '';

    # ghostty color template
    "${config.xdg.configHome}/matugen/templates/ghostty-colors.conf".text = ''
      # Ghostty colors generated by matugen
      background = {{colors.background.default.hex}}
      foreground = {{colors.on_background.default.hex}}
      cursor-color = {{colors.primary.default.hex}}
      cursor-text = {{colors.on_primary.default.hex}}
      selection-background = {{colors.secondary_container.default.hex}}
      selection-foreground = {{colors.on_secondary_container.default.hex}}
      search-background = {{colors.tertiary.default.hex}}
      search-foreground = {{colors.on_tertiary.default.hex}}
      search-selected-background = {{colors.primary.default.hex}}
      search-selected-foreground = {{colors.on_primary.default.hex}}
      split-divider-color = {{colors.outline_variant.default.hex}}
      unfocused-split-fill = {{colors.surface_container_low.default.hex}}
      
      palette = 0={{colors.surface.default.hex}}
      palette = 1={{colors.error.default.hex}}
      palette = 2={{colors.tertiary.default.hex}}
      palette = 3={{colors.secondary.default.hex}}
      palette = 4={{colors.primary.default.hex}}
      palette = 5={{colors.inverse_primary.default.hex}}
      palette = 6={{colors.primary_fixed_dim.default.hex}}
      palette = 7={{colors.on_surface.default.hex}}
      palette = 8={{colors.outline.default.hex}}
      palette = 9={{colors.error.default.hex}}
      palette = 10={{colors.tertiary.default.hex}}
      palette = 11={{colors.secondary.default.hex}}
      palette = 12={{colors.primary.default.hex}}
      palette = 13={{colors.inverse_primary.default.hex}}
      palette = 14={{colors.primary_fixed_dim.default.hex}}
      palette = 15={{colors.on_surface.default.hex}}
    '';

    # oh-my-posh wallpaper override template
    "${config.xdg.configHome}/matugen/templates/ohmyposh-wallpaper.json".text = ''
      {
        "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
        "extends": "${config.xdg.configHome}/oh-my-posh/ohmyposh-default.json",
        "final_space": true,
        "palette": {
          "black": "{{colors.background.default.hex}}",
          "blue": "{{colors.primary.default.hex}}",
          "green": "{{colors.tertiary.default.hex}}",
          "orange": "{{colors.secondary.default.hex}}",
          "red": "{{colors.error.default.hex}}",
          "white": "{{colors.on_surface.default.hex}}",
          "yellow": "{{colors.primary_container.default.hex}}",
          "userFg": "{{colors.on_primary_container.default.hex}}",
          "userBg": "{{colors.primary_container.default.hex}}",
          "dirFg": "{{colors.on_secondary_container.default.hex}}",
          "dirBg": "{{colors.secondary_container.default.hex}}",
          "statusOkFg": "{{colors.on_tertiary.default.hex}}",
          "statusOkBg": "{{colors.tertiary.default.hex}}",
          "statusErrFg": "{{colors.on_error.default.hex}}",
          "statusErrBg": "{{colors.error.default.hex}}",
          "gitAhead": "{{colors.tertiary.default.hex}}",
          "gitBehind": "{{colors.error.default.hex}}"
        }
      }
    '';

    # tmux color template
    "${config.xdg.configHome}/matugen/templates/tmux-colors.conf".text = ''
      # tmux colors generated by matugen
      set -g @matugen_bg '{{colors.background.default.hex}}'
      set -g @matugen_surface '{{colors.surface.default.hex}}'
      set -g @matugen_surface_alt '{{colors.surface_container_high.default.hex}}'
      set -g @matugen_fg '{{colors.on_surface.default.hex}}'
      set -g @matugen_accent '{{colors.primary.default.hex}}'
      set -g @matugen_accent_alt '{{colors.tertiary.default.hex}}'
      set -g @matugen_border '{{colors.outline_variant.default.hex}}'
      set -g @matugen_urgent '{{colors.error.default.hex}}'

      set -g status-style "bg=default,fg=#{@matugen_fg}"
      set -g message-style "bg=default,fg=#{@matugen_accent}"
      set -g message-command-style "bg=default,fg=#{@matugen_accent_alt}"
      set -g pane-border-style "fg=#{@matugen_border}"
      set -g pane-active-border-style "fg=#{@matugen_accent}"
      set -g status-left-style "bg=default,fg=#{@matugen_accent}"
      set -g status-right-style "bg=default,fg=#{@matugen_fg}"
      set -g window-status-style "bg=default,fg=#{@matugen_fg}"
      set -g window-status-current-style "bg=default,fg=#{@matugen_accent_alt},bold"
      set -g window-status-activity-style "bg=default,fg=#{@matugen_accent}"
      set -g window-status-bell-style "bg=default,fg=#{@matugen_urgent},bold"
    '';

    # Neovim wallpaper theme template
    "${config.xdg.configHome}/matugen/templates/nvim-matugen.lua".text = ''
      -- Neovim colors generated by matugen
      local c = {
        bg = "{{colors.background.default.hex}}",
        surface = "{{colors.surface.default.hex}}",
        surface_alt = "{{colors.surface_container_high.default.hex}}",
        fg = "{{colors.on_surface.default.hex}}",
        muted = "{{colors.outline.default.hex}}",
        border = "{{colors.outline_variant.default.hex}}",
        accent = "{{colors.primary.default.hex}}",
        accent_alt = "{{colors.tertiary.default.hex}}",
        accent_soft = "{{colors.secondary_container.default.hex}}",
        on_accent = "{{colors.on_primary.default.hex}}",
        ok = "{{colors.secondary.default.hex}}",
        warn = "{{colors.tertiary.default.hex}}",
        err = "{{colors.error.default.hex}}",
      }

      vim.o.termguicolors = true
      vim.g.colors_name = "matugen-wallpaper"

      local set = vim.api.nvim_set_hl
      set(0, "Normal", { fg = c.fg, bg = c.bg })
      set(0, "NormalFloat", { fg = c.fg, bg = c.surface })
      set(0, "FloatBorder", { fg = c.accent, bg = c.surface })
      set(0, "WinSeparator", { fg = c.border, bg = c.bg })
      set(0, "CursorLine", { bg = c.surface })
      set(0, "CursorLineNr", { fg = c.accent, bold = true })
      set(0, "Visual", { bg = c.accent_soft, fg = c.fg })
      set(0, "Search", { bg = c.accent, fg = c.on_accent })
      set(0, "IncSearch", { bg = c.accent_alt, fg = c.bg })
      set(0, "LineNr", { fg = c.muted })
      set(0, "Pmenu", { fg = c.fg, bg = c.surface })
      set(0, "PmenuSel", { fg = c.on_accent, bg = c.accent })
      set(0, "PmenuSbar", { bg = c.surface_alt })
      set(0, "PmenuThumb", { bg = c.accent_alt })
      set(0, "StatusLine", { fg = c.fg, bg = c.surface_alt })
      set(0, "StatusLineNC", { fg = c.muted, bg = c.surface })
      set(0, "TabLine", { fg = c.fg, bg = c.surface })
      set(0, "TabLineSel", { fg = c.on_accent, bg = c.accent })
      set(0, "TabLineFill", { bg = c.bg })
      set(0, "DiagnosticError", { fg = c.err })
      set(0, "DiagnosticWarn", { fg = c.warn })
      set(0, "DiagnosticInfo", { fg = c.accent })
      set(0, "DiagnosticHint", { fg = c.ok })
      set(0, "DiagnosticVirtualTextError", { fg = c.err, bg = c.surface })
      set(0, "DiagnosticVirtualTextWarn", { fg = c.warn, bg = c.surface })
      set(0, "DiagnosticVirtualTextInfo", { fg = c.accent, bg = c.surface })
      set(0, "DiagnosticVirtualTextHint", { fg = c.ok, bg = c.surface })
      set(0, "BufferLineFill", { bg = c.bg })
      set(0, "BufferLineBackground", { fg = c.muted, bg = c.surface })
      set(0, "BufferLineBufferSelected", { fg = c.fg, bg = c.surface_alt, bold = true })
      set(0, "BufferLineIndicatorSelected", { fg = c.accent, bg = c.surface_alt })
      set(0, "BufferLineSeparator", { fg = c.bg, bg = c.bg })
      set(0, "BufferLineSeparatorSelected", { fg = c.bg, bg = c.surface_alt })
      set(0, "NoiceCmdlinePopupBorder", { fg = c.accent, bg = c.surface })
      set(0, "NoiceConfirmBorder", { fg = c.accent_alt, bg = c.surface })
      set(0, "NotifyBackground", { bg = c.surface })

      return c
    '';

    # OpenCode theme template
    "${config.xdg.configHome}/matugen/templates/opencode-theme.json".text = ''
      {
        "$schema": "https://opencode.ai/theme.json",
        "theme": {
        "primary": "{{colors.primary.default.hex}}",
        "secondary": "{{colors.tertiary.default.hex}}",
        "accent": "{{colors.primary_container.default.hex}}",
        "text": "{{colors.on_surface.default.hex}}",
        "textMuted": "{{colors.outline.default.hex}}",
        "background": "none",
        "backgroundPanel": "none",
        "backgroundElement": "none",
          "border": "{{colors.outline_variant.default.hex}}",
          "borderActive": "{{colors.primary.default.hex}}",
          "borderSubtle": "{{colors.surface_container_highest.default.hex}}",
          "error": "{{colors.error.default.hex}}",
          "warning": "{{colors.secondary.default.hex}}",
          "success": "{{colors.primary.default.hex}}",
          "info": "{{colors.tertiary.default.hex}}",
          "diffAdded": "{{colors.primary.default.hex}}",
          "diffRemoved": "{{colors.error.default.hex}}",
          "diffContext": "{{colors.outline.default.hex}}",
          "diffHunkHeader": "{{colors.tertiary.default.hex}}",
          "diffHighlightAdded": "{{colors.primary_container.default.hex}}",
          "diffHighlightRemoved": "{{colors.error_container.default.hex}}",
          "diffAddedBg": "{{colors.primary_container.default.hex}}",
          "diffRemovedBg": "{{colors.error_container.default.hex}}",
          "diffContextBg": "{{colors.surface.default.hex}}",
          "diffLineNumber": "{{colors.outline.default.hex}}",
          "diffAddedLineNumberBg": "{{colors.primary_fixed_dim.default.hex}}",
          "diffRemovedLineNumberBg": "{{colors.error.default.hex}}",
          "syntaxComment": "{{colors.outline.default.hex}}",
          "syntaxKeyword": "{{colors.tertiary.default.hex}}",
          "syntaxFunction": "{{colors.primary.default.hex}}",
          "syntaxVariable": "{{colors.on_surface.default.hex}}",
          "syntaxString": "{{colors.secondary.default.hex}}",
          "syntaxNumber": "{{colors.tertiary.default.hex}}",
          "syntaxType": "{{colors.primary_fixed_dim.default.hex}}",
          "syntaxOperator": "{{colors.primary.default.hex}}",
          "syntaxPunctuation": "{{colors.outline.default.hex}}"
        }
      }
    '';
  };

  # Hyprland is the only scope that opts cross-desktop apps into mutable
  # matugen theme fragments. Common app modules intentionally remain unaware of
  # these files so i3 and Darwin keep their normal/default app behavior.
  programs.ghostty.settings.config-file =
    "?${config.xdg.configHome}/ghostty/colors.conf";

  programs.oh-my-posh.configFile =
    "${config.xdg.configHome}/oh-my-posh/wallpaper.json";

  programs.tmux.extraConfig = lib.mkAfter ''
    # Load Hyprland-owned wallpaper colors if matugen has produced them.
    if-shell "test -f ${config.xdg.configHome}/tmux/tmux-colors.conf" \
      "source-file ${config.xdg.configHome}/tmux/tmux-colors.conf"
  '';

  programs.nixvim.extraConfigLua = lib.mkAfter ''
    -- Matugen wallpaper theme.
    --
    -- The wallpaper rotation script re-`dofile`s the generated matugen.lua
    -- when the wallpaper changes and then sends SIGUSR1 to every running nvim
    -- so the highlights and lualine theme pick up the new palette without
    -- needing to restart the editor. See users/austin/nixos/hyprland/awww.nix
    -- for the signal send.
    local function apply_matugen_theme()
      local ok, result = pcall(dofile, vim.fn.expand("${config.xdg.configHome}/nvim/lua/generated/matugen.lua"))
      if not ok or type(result) ~= "table" then
        return
      end
      local colors = result

      local transparent_bg = ${if pkgs.stdenv.isLinux then "true" else "false"}

      if transparent_bg then
        local set = vim.api.nvim_set_hl
        set(0, "Normal", { fg = colors.fg, bg = "NONE" })
        set(0, "NormalNC", { fg = colors.fg, bg = "NONE" })
        set(0, "EndOfBuffer", { fg = colors.bg, bg = "NONE" })
        set(0, "SignColumn", { bg = "NONE" })
        set(0, "FoldColumn", { bg = "NONE" })
        set(0, "LineNr", { fg = colors.muted, bg = "NONE" })
      end

      local ok_lualine, lualine = pcall(require, "lualine")
      if ok_lualine then
        lualine.setup({
          options = {
            theme = {
              normal = {
                a = { bg = colors.accent, fg = colors.on_accent, gui = "bold" },
                b = { bg = colors.surface_alt, fg = colors.fg },
                c = { bg = colors.surface, fg = colors.fg },
              },
              insert = {
                a = { bg = colors.accent_alt, fg = colors.bg, gui = "bold" },
                b = { bg = colors.surface_alt, fg = colors.fg },
              },
              visual = {
                a = { bg = colors.warn, fg = colors.bg, gui = "bold" },
                b = { bg = colors.surface_alt, fg = colors.fg },
              },
              replace = {
                a = { bg = colors.err, fg = colors.bg, gui = "bold" },
                b = { bg = colors.surface_alt, fg = colors.fg },
              },
              inactive = {
                a = { bg = colors.surface, fg = colors.muted },
                b = { bg = colors.surface, fg = colors.muted },
                c = { bg = colors.surface, fg = colors.muted },
              },
            },
          },
        })
      end
    end

    -- Initial application at startup.
    apply_matugen_theme()

    -- Live-reload handler. The wallpaper rotation script sends SIGUSR1 after
    -- regenerating matugen.lua, so this re-`dofile`s the file and re-applies
    -- the highlights/lualine theme against the new palette.
    vim.api.nvim_create_autocmd("Signal", {
      pattern = "SIGUSR1",
      group = vim.api.nvim_create_augroup("MatugenLiveReload", { clear = true }),
      callback = function()
        apply_matugen_theme()
        vim.schedule(function()
          vim.cmd("redraw!")
        end)
      end,
    })
  '';

  # Ensure directories exist
  home.activation.createMatugenDirs = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p "${config.xdg.configHome}/matugen/templates"
    mkdir -p "${config.xdg.cacheHome}/matugen"
    mkdir -p "${config.xdg.configHome}/waybar"
    mkdir -p "${config.xdg.configHome}/wlogout"
    mkdir -p "${config.xdg.configHome}/mako"
    mkdir -p "${config.xdg.configHome}/wofi"
    mkdir -p "${config.xdg.configHome}/ghostty"
    mkdir -p "${config.xdg.configHome}/oh-my-posh"
    mkdir -p "${config.xdg.configHome}/tmux"
    mkdir -p "${config.xdg.configHome}/nvim/lua/generated"
    mkdir -p "${config.xdg.configHome}/opencode/themes"
  '';

  # Seed matugen outputs before Hyprland starts so `source = ...` is always valid.
  # Prefer a real random wallpaper from Favorites; fall back to a minimal valid file.
  home.activation.seedMatugenTheme = lib.hm.dag.entryAfter [ "createMatugenDirs" ] ''
    cache_dir="${config.xdg.cacheHome}/matugen"
    hypr_file="$cache_dir/hyprland-colors.conf"
    ghostty_file="${config.xdg.configHome}/ghostty/colors.conf"
    ohmyposh_file="${config.xdg.configHome}/oh-my-posh/wallpaper.json"
    tmux_file="${config.xdg.configHome}/tmux/tmux-colors.conf"
    nixvim_file="${config.xdg.configHome}/nvim/lua/generated/matugen.lua"
    waybar_file="${config.xdg.configHome}/waybar/colors.css"
    wlogout_file="${config.xdg.configHome}/wlogout/colors.css"
    mako_file="${config.xdg.configHome}/mako/config"
    wofi_file="${config.xdg.configHome}/wofi/colors.css"
    wallpaper_dir="${wallpaperDir}"
    seeded=0

    mkdir -p "$cache_dir"

    if [ -d "$wallpaper_dir" ]; then
      wallpaper="$(${pkgs.findutils}/bin/find "$wallpaper_dir" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) | ${pkgs.coreutils}/bin/shuf -n 1 || true)"

      if [ -n "$wallpaper" ]; then
        if ${pkgs.matugen}/bin/matugen image "$wallpaper" \
          --source-color-index 0 \
          --config "${config.xdg.configHome}/matugen/config.toml"; then
          if [ -s "$hypr_file" ]; then
            seeded=1
          fi
        fi
      fi
    fi

    if [ "$seeded" -ne 1 ]; then
      printf '%s\n' '# fallback matugen seed file' > "$hypr_file"
    fi

    if [ ! -s "$ghostty_file" ]; then
      printf '%s\n' \
        '# fallback Ghostty matugen seed file' \
        'background = #1e1e2e' \
        'foreground = #cdd6f4' \
        'cursor-color = #cba6f7' \
        'cursor-text = #1e1e2e' \
        'selection-background = #45475a' \
        'selection-foreground = #cdd6f4' \
        'search-background = #f9e2af' \
        'search-foreground = #1e1e2e' \
        'search-selected-background = #cba6f7' \
        'search-selected-foreground = #1e1e2e' \
        'split-divider-color = #45475a' \
        'unfocused-split-fill = #313244' \
        'palette = 0=#45475a' \
        'palette = 1=#f38ba8' \
        'palette = 2=#a6e3a1' \
        'palette = 3=#f9e2af' \
        'palette = 4=#89b4fa' \
        'palette = 5=#cba6f7' \
        'palette = 6=#94e2d5' \
        'palette = 7=#bac2de' \
        'palette = 8=#585b70' \
        'palette = 9=#f38ba8' \
        'palette = 10=#a6e3a1' \
        'palette = 11=#f9e2af' \
        'palette = 12=#89b4fa' \
        'palette = 13=#cba6f7' \
        'palette = 14=#94e2d5' \
        'palette = 15=#cdd6f4' \
        > "$ghostty_file"
    fi

    if [ ! -s "$ohmyposh_file" ]; then
      printf '%s\n' \
        '{' \
        '  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",' \
        '  "extends": "${config.xdg.configHome}/oh-my-posh/ohmyposh-default.json",' \
        '  "final_space": true' \
        '}' \
        > "$ohmyposh_file"
    fi

    if [ ! -s "$tmux_file" ]; then
      printf '%s\n' \
        '# fallback tmux matugen seed file' \
        "set -g @matugen_bg '#1e1e2e'" \
        "set -g @matugen_surface '#313244'" \
        "set -g @matugen_surface_alt '#45475a'" \
        "set -g @matugen_fg '#cdd6f4'" \
        "set -g @matugen_accent '#cba6f7'" \
        "set -g @matugen_accent_alt '#94e2d5'" \
        "set -g @matugen_border '#585b70'" \
        "set -g @matugen_urgent '#f38ba8'" \
        "set -g status-style 'bg=default,fg=#{@matugen_fg}'" \
        "set -g message-style 'bg=default,fg=#{@matugen_accent}'" \
        "set -g message-command-style 'bg=default,fg=#{@matugen_accent_alt}'" \
        "set -g pane-border-style 'fg=#{@matugen_border}'" \
        "set -g pane-active-border-style 'fg=#{@matugen_accent}'" \
        "set -g status-left-style 'bg=default,fg=#{@matugen_accent}'" \
        "set -g status-right-style 'bg=default,fg=#{@matugen_fg}'" \
        "set -g window-status-style 'bg=default,fg=#{@matugen_fg}'" \
        "set -g window-status-current-style 'bg=default,fg=#{@matugen_accent_alt},bold'" \
        "set -g window-status-activity-style 'bg=default,fg=#{@matugen_accent}'" \
        "set -g window-status-bell-style 'bg=default,fg=#{@matugen_urgent},bold'" \
        > "$tmux_file"
    fi

    if [ ! -s "$nixvim_file" ]; then
      printf '%s\n' \
        '-- fallback Neovim matugen seed file' \
        'return {' \
        '  bg = "#1e1e2e",' \
        '  surface = "#313244",' \
        '  surface_alt = "#45475a",' \
        '  fg = "#cdd6f4",' \
        '  muted = "#6c7086",' \
        '  border = "#585b70",' \
        '  accent = "#cba6f7",' \
        '  accent_alt = "#94e2d5",' \
        '  accent_soft = "#45475a",' \
        '  on_accent = "#1e1e2e",' \
        '  ok = "#a6e3a1",' \
        '  warn = "#f9e2af",' \
        '  err = "#f38ba8",' \
        '}' \
        > "$nixvim_file"
    fi

    if [ ! -s "$waybar_file" ]; then
      printf '%s\n' \
        '/* fallback Waybar matugen seed file */' \
        '@define-color bg #1e1e2e;' \
        '@define-color surface #313244;' \
        '@define-color surface-alt #45475a;' \
        '@define-color fg #cdd6f4;' \
        '@define-color accent #cba6f7;' \
        '@define-color accent-alt #94e2d5;' \
        '@define-color accent-soft #45475a;' \
        '@define-color on-accent #1e1e2e;' \
        '@define-color muted #6c7086;' \
        '@define-color border #585b70;' \
        '@define-color warning #f9e2af;' \
        '@define-color urgent #f38ba8;' \
        '* { color: @fg; }' \
        '#workspaces button.active { background-color: @accent; color: @on-accent; }' \
        '#battery.warning,' \
        '#temperature.critical,' \
        '#network.disconnected { background-color: @warning; color: @bg; }' \
        > "$waybar_file"
    fi

    if [ ! -s "$wlogout_file" ]; then
      printf '%s\n' \
        '/* fallback wlogout matugen seed file */' \
        '@define-color bg #1e1e2e;' \
        '@define-color surface #313244;' \
        '@define-color surface-alt #45475a;' \
        '@define-color fg #cdd6f4;' \
        '@define-color accent #cba6f7;' \
        '@define-color accent-alt #94e2d5;' \
        '@define-color on-accent #1e1e2e;' \
        '@define-color border #585b70;' \
        '@define-color urgent #f38ba8;' \
        > "$wlogout_file"
    fi

    if [ ! -s "$mako_file" ]; then
      printf '%s\n' \
        '# fallback mako matugen seed file' \
        'background-color=#313244' \
        'text-color=#cdd6f4' \
        'border-color=#cba6f7' \
        'progress-color=over #45475a' \
        'default-timeout=5000' \
        'group-by=summary' \
        'max-visible=5' \
        'border-size=2' \
        'border-radius=8' \
        'font=Sans 10' \
        > "$mako_file"
    fi

    if [ ! -s "$wofi_file" ]; then
      printf '%s\n' \
        '/* fallback wofi matugen seed file */' \
        'window { background-color: #313244; color: #cdd6f4; border: 2px solid #cba6f7; border-radius: 12px; }' \
        '#input { background-color: #45475a; color: #cdd6f4; border: 2px solid #585b70; border-radius: 10px; margin: 10px; padding: 10px 12px; }' \
        '#inner-box { margin: 8px; }' \
        '#entry { border-radius: 10px; margin: 4px 8px; padding: 10px 12px; }' \
        '#entry:nth-child(even) { background-color: #45475a; }' \
        '#entry:selected { background-color: #cba6f7; color: #1e1e2e; outline: none; }' \
        '#text:selected,' \
        '#img:selected { color: #1e1e2e; }' \
        > "$wofi_file"
    fi
  '';
}
